import {
  FaMountain, FaHiking, FaLanguage, FaHeart, FaMusic, FaCamera,
  FaPlane, FaUtensils, FaBook, FaGlobe, FaSave, FaPlus, FaTrash,
  FaCode, FaGamepad, FaFilm, FaDumbbell, FaPalette, FaLaptopCode,
  FaCoffee, FaBeer, FaBasketballBall, FaBiking, FaDog, FaTree,
  FaStar, FaMoon, FaSun, FaLeaf, FaAnchor, FaTheaterMasks,
  FaSwimmingPool, FaFire, FaSnowflake, FaCity, FaBicycle,
  FaUser, FaMapMarkedAlt, FaEnvelope, FaPhone, FaFlag, FaMapMarkerAlt,FaCity as FaCityIcon
} from 'react-icons/fa';

export const availableIcons = [
    { name: 'FaHiking', component: <FaHiking /> },
    { name: 'FaCamera', component: <FaCamera /> },
    { name: 'FaPlane', component: <FaPlane /> },
    { name: 'FaUtensils', component: <FaUtensils /> },
    { name: 'FaMusic', component: <FaMusic /> },
    { name: 'FaBook', component: <FaBook /> },
    { name: 'FaGlobe', component: <FaGlobe /> },
    { name: 'FaHeart', component: <FaHeart /> },
    { name: 'FaCode', component: <FaCode /> },
    { name: 'FaGamepad', component: <FaGamepad /> },
    { name: 'FaFilm', component: <FaFilm /> },
    { name: 'FaDumbbell', component: <FaDumbbell /> },
    { name: 'FaPalette', component: <FaPalette /> },
    { name: 'FaLaptopCode', component: <FaLaptopCode /> },
    { name: 'FaCoffee', component: <FaCoffee /> },
    { name: 'FaBeer', component: <FaBeer /> },
    { name: 'FaBasketballBall', component: <FaBasketballBall /> },
    { name: 'FaBiking', component: <FaBiking /> },
    { name: 'FaDog', component: <FaDog /> },
    { name: 'FaTree', component: <FaTree /> },
    { name: 'FaStar', component: <FaStar /> },
    { name: 'FaMoon', component: <FaMoon /> },
    { name: 'FaSun', component: <FaSun /> },
    { name: 'FaLeaf', component: <FaLeaf /> },
    { name: 'FaAnchor', component: <FaAnchor /> },
    { name: 'FaTheaterMasks', component: <FaTheaterMasks /> },
    { name: 'FaSwimmingPool', component: <FaSwimmingPool /> },
    { name: 'FaFire', component: <FaFire /> },
    { name: 'FaSnowflake', component: <FaSnowflake /> },
    { name: 'FaCity', component: <FaCity /> },
    { name: 'FaBicycle', component: <FaBicycle /> },
  ];